### ISSUE TITLE
unsupported version of postgresql: 10.9

### ISSUE THREAD

**Issue by hjaffan** [cloudfoundry-incubator/bosh-backup-and-restore#30]
When running bbr against BOSH 268.6.4 we get that the version of PostgreSQL 10.9 is unsupported.

**Comment by alamages** [comment]
Hello @hjaffan, thanks for reporting this.

This issue though is not tight to `bbr` cli. `bbr` is just an orchestrator which invokes backup and restore scripts on the target director or deployment. In this case, it's the backup and restore scripts of the deployed director which fail with the following message. The cli can not address this.

The issue you describe is related with [backup-and-restore-sdk-release](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release) though. BOSH is using internally this release to backup its postgres database. It seems that the backup-and-restore-sdk-release your deployed BOSH is using does not support postgres 10.9. If you check the release notes, the [sdk v1.15.0](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/releases/tag/v1.15.0) introduces support for Postgres v10.x.

You just need to bump the sdk release your director is using to a version >= v1.15.0. For example, if you check the bosh-deployment repo, this [ops-file](https://github.com/cloudfoundry/bosh-deployment/blob/master/bbr.yml) templates the latest sdk v1.17.0. 

I am closing this issue since it not related to bbr.
